# --------------------------------------------
# DDL for Table STUDENT_PERSONAL
# --------------------------------------------
CREATE TABLE STUDENT_PERSONAL
(
    ID            BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    TC_NO         CHAR(11) UNIQUE,
    STATUS        CHAR(1) NOT NULL CHECK (STATUS IN ('P', 'A', 'D')),
    NAME          VARCHAR(255),
    SURNAME       VARCHAR(255),
    EMAIL         VARCHAR(200),
    PHONE_NUMBER  CHAR(11),
    ADDRESS       VARCHAR(255),
    BIRTHDAY      DATE,
    CREATED_DATE  TIMESTAMP,
    CREATED_USER  DECIMAL(12),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_USER DECIMAL(12)
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table STUDENT_ACADEMIC
# --------------------------------------------
CREATE TABLE STUDENT_ACADEMIC
(
    ID            BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    FACULTY_ID    DECIMAL(4) UNIQUE,
    DEPARTMENT_ID DECIMAL(3) UNIQUE,
    DEGREE_ID     DECIMAL(6) UNIQUE,
    CLASS         VARCHAR(20),
    STATUS        CHAR(1) NOT NULL CHECK (STATUS IN ('P', 'A', 'D')),
    EMAIL         VARCHAR(200),
    REGISTRATION_DATE DATE,
    CREATED_DATE  TIMESTAMP,
    CREATED_USER  DECIMAL(12),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_USER DECIMAL(12)
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table STUDENT_DEGREE
# --------------------------------------------
CREATE TABLE STUDENT_DEGREE
(
    ID            BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    NAME          VARCHAR(255),
    CREATED_DATE  TIMESTAMP,
    CREATED_USER  DECIMAL(12),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_USER DECIMAL(12)
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table STUDENT_GRADUATION
# --------------------------------------------
CREATE TABLE STUDENT_GRADUATION
(
    ID            BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    STUDENT_ID    DECIMAL(12) UNIQUE,
    DEPARTMENT_ID DECIMAL(3) UNIQUE,
    STATUS        CHAR(1) NOT NULL CHECK (STATUS IN ('P', 'A', 'D')),
    CREATED_DATE  TIMESTAMP,
    CREATED_USER  DECIMAL(12),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_USER DECIMAL(12)
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table STUDENT_LESSON_ABSENTEEISM
# --------------------------------------------
CREATE TABLE STUDENT_LESSON_ABSENTEEISM
(
    ID            BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    STUDENT_ID    DECIMAL(12) UNIQUE,
    LESSON_ID     DECIMAL(10) UNIQUE,
    THEORY_TIME   DECIMAL(15),
    PRACTICE_TIME DECIMAL(15),
    STATUS        CHAR(1) NOT NULL CHECK (STATUS IN ('P', 'A', 'D')),
    CREATED_DATE  TIMESTAMP,
    CREATED_USER  DECIMAL(12),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_USER DECIMAL(12)
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table STUDENT_LESSON_REGISTRATION
# --------------------------------------------
CREATE TABLE STUDENT_LESSON_REGISTRATION
(
    ID            BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    STUDENT_ID    DECIMAL(12) UNIQUE,
    LESSON_ID     DECIMAL(10) UNIQUE,
    STATUS        CHAR(1) NOT NULL CHECK (STATUS IN ('P', 'A', 'D')),
    CREATED_DATE  TIMESTAMP,
    CREATED_USER  VARCHAR(25),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_USER VARCHAR(25)
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table STUDENT_INTERN_INFO
# --------------------------------------------
CREATE TABLE STUDENT_INTERN_INFO
(
    ID            BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    STUDENT_ID    DECIMAL(12) UNIQUE,
    COMPANY_NAME  VARCHAR(250),
    STATUS        CHAR(1) NOT NULL CHECK (STATUS IN ('P', 'A', 'D')),
    INTERN_START_DATE      DATE,
    INTERN_END_DATE        DATE,
    CREATED_DATE  TIMESTAMP,
    CREATED_USER  DECIMAL(12),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_USER DECIMAL(12)
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table LESSON
# --------------------------------------------
CREATE TABLE LESSON
(
    ID            BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    NAME          VARCHAR(250),
    CLASS         VARCHAR(20),
    MIDTERM       VARCHAR(20),
    CREDIT        VARCHAR(15),
    COMPULSORY_OR_ELECTIVE CHAR(1) NOT NULL CHECK (STATUS IN ('S','Z')),
    STATUS        CHAR(1) NOT NULL CHECK (STATUS IN ('P', 'A', 'D')),
    CREATED_DATE  TIMESTAMP,
    CREATED_USER  DECIMAL(12),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_USER DECIMAL(12)
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table LESSON_TIME_PERCENT
# --------------------------------------------
CREATE TABLE LESSON_TIME_PERCENT
(
    ID            BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    LESSON_ID DECIMAL(10) UNIQUE,
    THEORY_TIME DECIMAL(15),
    THEORY_TIME_PERCENT DECIMAL(15),
    PRACTICE_TIME DECIMAL(15),
    PRACTICE_TIME_PERCENT DECIMAL(15),
    TOTAL_TIME DECIMAL(15),
    CREATED_DATE  TIMESTAMP,
    CREATED_USER  DECIMAL(12),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_USER DECIMAL(12)
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table LESSON_SCHEDULE
# --------------------------------------------
CREATE TABLE LESSON_SCHEDULE
(
    ID            BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    DEPARTMENT_ID DECIMAL(3) UNIQUE,
    CREATED_DATE  TIMESTAMP,
    CREATED_USER  DECIMAL(12),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_USER DECIMAL(12)
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table EXAM_SCHEDULE
# --------------------------------------------
CREATE TABLE EXAM_SCHEDULE
(
    ID            BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    DEPARTMENT_ID DECIMAL(3) UNIQUE,
    CREATED_DATE  TIMESTAMP,
    CREATED_USER  DECIMAL(12),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_USER DECIMAL(12)
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table LESSON_EXAM_PERCENT
# --------------------------------------------
CREATE TABLE LESSON_EXAM_PERCENT
(
    ID            BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    LESSON_ID DECIMAL(10) UNIQUE,
    MIDTERM_NOTE_PERCENT DECIMAL(20),
    FINAL_NOTE_PERCENT DECIMAL(20),
    CREATED_DATE  TIMESTAMP,
    CREATED_USER  DECIMAL(12),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_USER DECIMAL(12)
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table STUDENT_LESSON_NOTE
# --------------------------------------------
CREATE TABLE STUDENT_LESSON_NOTE
(
    ID            BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    STUDENT_ID DECIMAL(12) UNIQUE,
    LESSON_ID DECIMAL(10) UNIQUE,
    MIDTERM_NOTE FLOAT(30),
    FINAL_NOTE FLOAT(30),
    RESIT_NOTE FLOAT(30),
    MEAN_OF_NOTE FLOAT(30),
    NOTE_STATUS CHAR(1) NOT NULL CHECK (STATUS IN ('K','G')),
    CREATED_DATE  TIMESTAMP,
    CREATED_USER  DECIMAL(12),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_USER DECIMAL(12)
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table FACULTY
# --------------------------------------------
CREATE TABLE FACULTY
(
    ID            BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    NAME          VARCHAR(255),
    STATUS        CHAR(1) NOT NULL CHECK (STATUS IN ('P', 'A', 'D')),
    CREATED_DATE  TIMESTAMP,
    CREATED_USER  DECIMAL(12),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_USER DECIMAL(12)
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table DEPARTMENT
# --------------------------------------------
CREATE TABLE DEPARTMENT
(
    ID            BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    NAME          VARCHAR(255),
    STATUS        CHAR(1) NOT NULL CHECK (STATUS IN ('P', 'A', 'D')),
    CREATED_DATE  TIMESTAMP,
    CREATED_USER  DECIMAL(12),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_USER DECIMAL(12)
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table STUDENT_PARAMETER
# --------------------------------------------
CREATE TABLE STUDENT_PARAMETER
(
    ID            BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    NAME          VARCHAR(255),
    VALUE         VARCHAR(20),
    CREATED_DATE  TIMESTAMP,
    CREATED_USER  DECIMAL(12),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_USER DECIMAL(12)
) TABLESPACE SIS_TBS;


