# --------------------------------------------
# DDL for Table AUTH_STUDENT_LOGIN
# --------------------------------------------
CREATE TABLE AUTH_STUDENT_LOGIN
(
    ID              BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    STUDENT_ID      NUMERIC(12) UNIQUE,
    PASSWORD        VARCHAR(512),
    FAIL_COUNTER    NUMERIC(1),
    LAST_LOGIN_DATE TIMESTAMP
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table AUTH_STUDENT_PASSWORD_OPERATION
# --------------------------------------------
CREATE TABLE AUTH_STUDENT_PASSWORD_OPERATION
(
    OPERATION_ID VARCHAR(36) PRIMARY KEY UNIQUE,
    STUDENT_ID   NUMERIC(12) UNIQUE,
    EXPIRE_DATE TIMESTAMP
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table AUTH_TEACHER_LOGIN
# --------------------------------------------
CREATE TABLE AUTH_TEACHER_LOGIN
(
    ID              BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    TEACHER_ID      NUMERIC(8) UNIQUE,
    PASSWORD        VARCHAR(512),
    FAIL_COUNTER    NUMERIC(1),
    LAST_LOGIN_DATE TIMESTAMP
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table AUTH_TEACHER_PASSWORD_OPERATION
# --------------------------------------------
CREATE TABLE AUTH_TEACHER_PASSWORD_OPERATION
(
    OPERATION_ID VARCHAR(36) PRIMARY KEY UNIQUE,
    TEACHER_ID   NUMERIC(8) UNIQUE,
    EXPIRE_DATE TIMESTAMP
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table AUTH_OFFICER_LOGIN
# --------------------------------------------
CREATE TABLE AUTH_OFFICER_LOGIN
(
    ID              BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    OFFICER_ID      NUMERIC(5) UNIQUE,
    PASSWORD        VARCHAR(512),
    FAIL_COUNTER    NUMERIC(1),
    LAST_LOGIN_DATE TIMESTAMP
) TABLESPACE SIS_TBS;

# --------------------------------------------
# DDL for Table AUTH_OFFICER_PASSWORD_OPERATION
# --------------------------------------------
CREATE TABLE AUTH_OFFICER_PASSWORD_OPERATION
(
    OPERATION_ID VARCHAR(36) PRIMARY KEY UNIQUE,
    OFFICER_ID   NUMERIC(5) UNIQUE,
    EXPIRE_DATE TIMESTAMP
) TABLESPACE SIS_TBS;


# --------------------------------------------
# CONSTRAINTS - FOREIGN KEYS
# --------------------------------------------
ALTER TABLE AUTH_STUDENT_LOGIN
    ADD CONSTRAINT AUTH_STUDENT_LOGIN_STUDENT_ID FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT_ACADEMIC_INFO (STUDENT_ID);

ALTER TABLE AUTH_STUDENT_PASSWORD_OPERATION
    ADD CONSTRAINT AUTH_STUDENT_PASSWORD_OPERATION_STUDENT_ID FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT_ACADEMIC_INFO (STUDENT_ID);

ALTER TABLE AUTH_TEACHER_LOGIN
    ADD CONSTRAINT AUTH_TEACHER_LOGIN_TEACHER_ID FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER_ACADEMIC_INFO (TEACHER_ID);

ALTER TABLE AUTH_TEACHER_PASSWORD_OPERATION
    ADD CONSTRAINT AUTH_TEACHER_PASSWORD_OPERATION_TEACHER_ID FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER_ACADEMIC_INFO (TEACHER_ID);

ALTER TABLE AUTH_OFFICER_LOGIN
    ADD CONSTRAINT AUTH_OFFICER_LOGIN_OFFICER_ID FOREIGN KEY (OFFICER_ID) REFERENCES OFFICER_ACADEMIC_INFO (OFFICER_ID);

ALTER TABLE AUTH_OFFICER_PASSWORD_OPERATION
    ADD CONSTRAINT AUTH_OFFICER_PASSWORD_OPERATION_OFFICER_ID FOREIGN KEY (OFFICER_ID) REFERENCES OFFICER_ACADEMIC_INFO (OFFICER_ID);
