INSERT INTO sis.UNIV_DEPARTMENT (ID, FACULTY_ID, NAME, STATUS, TOTAL_CLASS_LEVEL, IS_THERE_PREPARATORY_CLASS,
                                 CREATED_DATE, CREATED_USER_ID, MODIFIED_DATE, MODIFIED_USER_ID)
VALUES (11012, null, null, 'ACTIVE', null, null, null, null, null, null);