# --------------------------------------------
# Insert SQL for Table AUTH_STUDENT_LOGIN
# --------------------------------------------

INSERT INTO sis.AUTH_STUDENT_LOGIN (STUDENT_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('200011101210', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_STUDENT_LOGIN (STUDENT_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('200011101211', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_STUDENT_LOGIN (STUDENT_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('200011101212', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_STUDENT_LOGIN (STUDENT_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('200011101213', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_STUDENT_LOGIN (STUDENT_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('200011101214', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_STUDENT_LOGIN (STUDENT_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('200011101215', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_STUDENT_LOGIN (STUDENT_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('200011101216', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_STUDENT_LOGIN (STUDENT_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('200011101217', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_STUDENT_LOGIN (STUDENT_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('200011101218', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_STUDENT_LOGIN (STUDENT_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('200011101219', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);


# --------------------------------------------
# Insert SQL for Table AUTH_TEACHER_LOGIN
# --------------------------------------------

INSERT INTO sis.AUTH_TEACHER_LOGIN (TEACHER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('11012020', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_TEACHER_LOGIN (TEACHER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('11012021', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_TEACHER_LOGIN (TEACHER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('11012022', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_TEACHER_LOGIN (TEACHER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('11012023', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_TEACHER_LOGIN (TEACHER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('11012024', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_TEACHER_LOGIN (TEACHER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('11012025', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_TEACHER_LOGIN (TEACHER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('11012026', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_TEACHER_LOGIN (TEACHER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('11012027', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_TEACHER_LOGIN (TEACHER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('11012028', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_TEACHER_LOGIN (TEACHER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('11012029', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);


# --------------------------------------------
# Insert SQL for Table AUTH_OFFICER_LOGIN
# --------------------------------------------

INSERT INTO sis.AUTH_OFFICER_LOGIN (OFFICER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('12001', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_OFFICER_LOGIN (OFFICER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('12002', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_OFFICER_LOGIN (OFFICER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('12003', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_OFFICER_LOGIN (OFFICER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('12004', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_OFFICER_LOGIN (OFFICER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('12005', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_OFFICER_LOGIN (OFFICER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('12006', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_OFFICER_LOGIN (OFFICER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('12007', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_OFFICER_LOGIN (OFFICER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('12008', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_OFFICER_LOGIN (OFFICER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('12009', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);

INSERT INTO sis.AUTH_OFFICER_LOGIN (OFFICER_ID, PASSWORD, FAIL_COUNTER, LAST_LOGIN_DATE)
VALUES ('12010', '$2a$10$a7AiKMb5qZ0qOqe./GSuw.spReSZfkxVJt119l4fLGTafwDCcanNy', 0, null);
