SET GLOBAL log_bin_trust_function_creators = 1;

CREATE TABLESPACE AUTH ADD DATAFILE 'auth.ibd' Engine = InnoDB;
CREATE TABLESPACE AUTH_TBS ADD DATAFILE 'auth_tbs.ibd' Engine = InnoDB;

CREATE DATABASE IF NOT EXISTS auth;
CREATE USER IF NOT EXISTS auth IDENTIFIED BY 'authpass';
GRANT ALL PRIVILEGES ON auth.* TO 'auth';
FLUSH PRIVILEGES;

COMMIT;