SET GLOBAL log_bin_trust_function_creators = 1;

CREATE TABLESPACE SIS ADD DATAFILE 'sis.ibd' Engine = InnoDB;
CREATE TABLESPACE SIS_TBS ADD DATAFILE 'sis_tbs.ibd' Engine = InnoDB;

CREATE DATABASE IF NOT EXISTS sis;
CREATE USER IF NOT EXISTS sis IDENTIFIED BY 'sispass';
GRANT ALL PRIVILEGES ON sis.* TO 'sis';
FLUSH PRIVILEGES;

COMMIT;